version: "3"
services:
    precoapi:
        image: "precoapi:1.0.0"
        ports:
            - "8005:80"
        environment:
            - "ConnectionURL=mongodb://172.17.0.1:27017"
    produtoapi:
        image: "produtoapi:1.0.0"
        ports:
            - "8006:80"
        environment:
            - "ConnectionURL=mongodb://172.17.0.1:27017"
    apoloserver:
        image: "docker-unj-repo.softplan.com.br/unj/apoloserver:1.0.0"
        ports:
            - "8004:5000"
        depends_on:
            - "precoapi"
            - "produtoapi"
        environment:
            - "PRECO_INTROSPECT_URL=http://172.17.0.1:8005"
            - "PRODUTO_INTROSPECT_URL=http://172.17.0.1:8006"
            - "PATH_GRAPHQL=/graphql"
